### ISSUE TITLE
Errata sheets.

### ISSUE THREAD

**Issue by gryken2014** [mbset/Astronomical_Algorithms#1]
Hello,

I've found no error.

But are-you aware of the 2 errata sheets for the book ?

http://www.willbell.com/math/AA-First%20Ed.%20Errata.pdf
http://www.willbell.com/math/AA-Second%20Ed.%20Errata.pdf

Website : http://www.willbell.com/math/mc1.htm

**Comment by mbset** [comment]
Hey, thanks for the heads up.
